### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by kmontenegro** [casefoundation/weekly-roundup#2]
I'm able to create and preview a roundup but when I hit "send", I get a "Request failed with status code 500" error and the email is not sent.

**Comment by johnjones4** [comment]
That usually happens when there's an issue with the Sendgrid API key that you had to input during the Heroku one-click deploy. If you go into your Heroku app's dashboard, click "More" in the upper right-hand corner, and select "View logs" you can see what the error is happening behind the scenes. If it's a problem with the API key, you might see something like: 

```
Error: Unauthorized
    at Request.http [as _callback] (node_modules/@sendgrid/client/src/classes/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:186:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (node_modules/request/request.js:1163:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by johnjones4** [comment]
@kmontenegro just following up on this. Happy to continue helping you get this setup.

**Comment by kmontenegro** [comment]
Excellent! That was exactly it: once I deleted and created a new key in Sendgrid and updated the config in Heroku, works as expected. Thank you.
